version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: sachin
      POSTGRES_USER: sachin
      POSTGRES_PASSWORD: sachinram123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sachin"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: sh -c "while ! nc -z db 5432; do sleep 1; done && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
